[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = { "Referrer-Policy": "strict-origin-when-cross-origin" }
