[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/psp/paymentorders"
  to = "https://api.externalintegration.payex.com/psp/paymentorders"
  status = 200
  force = true


[[headers]]
  for = "/api/paymentorders"
  [headers.values]
    Content-Type = "application/json;version=3.1"
    Host = "api.externalintegration.payex.com"