[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/psp/*"
  to = "https://api.externalintegration.payex.com/paymentorders"
  status = 200
  force = true
  headers = {X-From = "Netlify"}